services:
  - type: web
    name: eospatras
    env: docker
    plan: free
    healthCheckPath: /health
    buildCommand: DOCKER_BUILDKIT=0 docker build -t eospatras .
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: postgresql://sillogosbase_user:SEk4MxnU8Q3FMQJupYHzwyXcNTScBTw9@dpg-d0lmge9r0fns738gu810-a.oregon-postgres.render.com/sillogosbase