services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "80:80"
    env:
      - DATABASE_URL=postgresql://sillogosbase_0ss9_user:T0QddYyleriq2YeaU80dmZ1aHPEnqGrV@dpg-d0mba43uibrs73eidmjg-a.oregon-postgres.render.com/sillogosbase_0ss9
      - NODE_ENV=production