services:
  frontend:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: dockerfile
      target: backend-build
    environment:
      - DATABASE_URL=postgresql://sillogosbase_user:SEk4MxnU8Q3FMQJupYHzwyXcNTScBTw9@dpg-d0lmge9r0fns738gu810-a.oregon-postgres.render.com/sillogosbase
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge