CREATE TABLE "epafes" (
  "id_epafis" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "onoma" varchar,
  "epitheto" varchar,
  "patronimo" varchar,
  "email" varchar,
  "tilefono" integer
);


CREATE TABLE "vathmos_diskolias" (
  "id_vathmou_diskolias" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "epipedo" varchar,
  "ores_poreias" integer,
  "ipsometriki_diafora" integer,
  "xioni" varchar,
  "skini" varchar
);


CREATE TABLE "eksormisi" (
  "id_eksormisis" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "proorismos" varchar,
  "timi" integer,
  "imerominia_anaxorisis" date,
  "imerominia_afiksis" date,
  "titlos" varchar
);


CREATE TABLE "katafigio" (
  "id_katafigiou" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "onoma" varchar,
  "xoritikotita" integer,
  "timi_melous" integer,
  "timi_mi_melous" integer
);


CREATE TABLE "eksoplismos" (
  "id_eksoplismou" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "onoma" varchar,
  "xroma" varchar,
  "imerominia_kataskeuis" date,
  "megethos" varchar,
  "marka" varchar
);


CREATE TABLE "athlima" (
  "id_athlimatos" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "onoma" varchar
);


CREATE TABLE "eidos_sindromis" (
  "id_eidous_sindromis" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "titlos" varchar,
  "timi" integer
);


CREATE TABLE "sxoli" (
  "id_sxolis" integer UNIQUE PRIMARY KEY,
  "timi" integer,
  "epipedo" varchar,
  "klados" varchar,
  "etos" integer,
  "seira" integer,
  "hmerominia_enarksis" date,
  "hmerominia_liksis" date,
  "topothesia" varchar
);


CREATE TABLE "Melos" (
  "id_melous" integer UNIQUE PRIMARY KEY,
  "id_vathmou_diskolias" integer
);


CREATE TABLE "esoteriko_melos" (
  "id_es_melous" integer UNIQUE PRIMARY KEY,
  "hmerominia_gennhshs" date,
  "patronimo" varchar,
  "odos" varchar,
  "tk" integer,
  "arithmos_mitroou" integer UNIQUE
);


CREATE TABLE "eksoteriko_melos" (
  "id_ekso_melous" integer UNIQUE PRIMARY KEY,
  "onoma_sillogou" varchar,
  "arithmos_mitroou" integer UNIQUE
);


CREATE TABLE "athlitis" (
  "id_athliti" integer PRIMARY KEY,
  "arithmos_deltiou" integer UNIQUE,
  "hmerominia_enarksis_deltiou" date,
  "hmerominia_liksis_deltiou" date
);


CREATE TABLE "sindromitis" (
  "id_sindromiti" integer UNIQUE PRIMARY KEY
);


CREATE TABLE "drastiriotita" (
  "id_drastiriotitas" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "id_eksormisis" integer,
  "id_vathmou_diskolias" integer,
  "ores_poreias" integer,
  "titlos" varchar,
  "diafora_ipsous" integer,
  "imerominia" date,
  "megisto_ipsometro" integer
);


CREATE TABLE "sindromi" (
  "id_sindromis" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "hmerominia_enarksis" date,
  "id_eidous_sindromis" integer
);


CREATE TABLE "ekpaideutis" (
  "id_ekpaideuti" integer UNIQUE PRIMARY KEY,
  "id_epafis" integer,
  "epipedo" varchar,
  "klados" varchar
);


CREATE TABLE "kratisi_katafigiou" (
  "id_kratisis" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "id_epafis" integer,
  "id_katafigiou" integer,
  "hmerominia_afiksis" date,
  "hmerominia_epistrofis" date,
  "ypoloipo" integer,
  "arithmos_melwn" integer,
  "arithmos_mi_melwn" integer,
  "atoma" integer,
  "imeres" integer,
  "sinoliki_timh" integer,
  "eksoterikos_xoros" varchar,
  "hmerominia_akirosis" date,
  "poso_epistrofis" integer,
  "hmerominia_kratisis" date
);


CREATE TABLE "daneizetai" (
  "id_epafis" integer,
  "id_eksoplismou" integer,
  "imerominia_daneismou" date,
  "imerominia_epistrofis" date,
  PRIMARY KEY (id_epafis,id_eksoplismou)
);


CREATE TABLE "eksoflei" (
  "id_epafis" integer,
  "id_kratisis" integer,
  "poso" integer,
  "hmerominia_eksoflisis" date,
  PRIMARY KEY (id_epafis,id_kratisis)
);


CREATE TABLE "exei" (
  "id_sindromiti" integer, 
  "id_sindromis" integer,
  "imerominia_pliromis" date,
  PRIMARY KEY (id_sindromiti,id_sindromis)
);


CREATE TABLE "asxoleitai" (
  "id_athliti" integer,
  "id_athlimatos" integer,
  PRIMARY KEY (id_athliti,id_athlimatos)
);


CREATE TABLE "agones" (
  "id_agona" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  "id_athlimatos" integer,
  "perigrafi" varchar,
  "hmerominia" date,
  "onoma" varchar,
  PRIMARY KEY ("id_agona", "id_athlimatos")
);


CREATE TABLE "agonizetai" (
  "id_athliti" integer,
  "id_agona" integer,
  PRIMARY KEY (id_athliti,id_agona)
);


CREATE TABLE "parakolouthisi" (
  "id_parakolouthisis" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "id_melous" integer,
  "id_sxolis" integer,
  "poso_epistrofis" integer,
  "timi" integer,
  "ypoloipo" integer,
  "katastasi" varchar,
  "hmerominia_dilosis" date,
  "hmerominia_akrirosis" date
);


CREATE TABLE "ekpaideuei" (
  "id_ekpaideuti" integer,
  "id_sxolis" integer,
  PRIMARY KEY (id_ekpaideuti,id_sxolis)
);


CREATE TABLE "simmetoxi" (
  "id_simmetoxis" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "id_melous" integer,
  "id_drastiriotitas" integer,
  "poso_epistrofis" integer,
  "timi" integer,
  "katastasi" varchar,
  "ypoloipo" integer,
  "imerominia_dilosis" date,
  "imerominia_akirosis" date
);


CREATE TABLE "plironei" (
  "id_melous" integer,
  "id_simmetoxis" integer,
  "imerominia_pliromis" date,
  "poso_pliromis" integer,
  PRIMARY KEY (id_melous,id_simmetoxis)
);


CREATE TABLE "katavalei" (
  "id_melous" integer,
  "id_parakolouthisis" integer,
  "poso" integer,
  "hmerominia_katavolhs" date,
  PRIMARY KEY (id_melous,id_parakolouthisis)
);

ALTER TABLE "Melos" ADD FOREIGN KEY ("id_melous") REFERENCES "epafes" ("id_epafis");

ALTER TABLE "Melos" ADD FOREIGN KEY ("id_vathmou_diskolias") REFERENCES "vathmos_diskolias" ("id_vathmou_diskolias");

ALTER TABLE "esoteriko_melos" ADD FOREIGN KEY ("id_es_melous") REFERENCES "Melos" ("id_melous");

ALTER TABLE "eksoteriko_melos" ADD FOREIGN KEY ("id_ekso_melous") REFERENCES "Melos" ("id_melous");

ALTER TABLE "athlitis" ADD FOREIGN KEY ("id_athliti") REFERENCES "esoteriko_melos" ("id_es_melous");

ALTER TABLE "sindromitis" ADD FOREIGN KEY ("id_sindromiti") REFERENCES "esoteriko_melos" ("id_es_melous");

ALTER TABLE "daneizetai" ADD FOREIGN KEY ("id_epafis") REFERENCES "epafes" ("id_epafis");

ALTER TABLE "daneizetai" ADD FOREIGN KEY ("id_eksoplismou") REFERENCES "eksoplismos" ("id_eksoplismou");

ALTER TABLE "kratisi_katafigiou" ADD FOREIGN KEY ("id_epafis") REFERENCES "epafes" ("id_epafis");

ALTER TABLE "kratisi_katafigiou" ADD FOREIGN KEY ("id_katafigiou") REFERENCES "katafigio" ("id_katafigiou");

ALTER TABLE "eksoflei" ADD FOREIGN KEY ("id_epafis") REFERENCES "epafes" ("id_epafis");

ALTER TABLE "eksoflei" ADD FOREIGN KEY ("id_kratisis") REFERENCES "kratisi_katafigiou" ("id_kratisis");

ALTER TABLE "asxoleitai" ADD FOREIGN KEY ("id_athliti") REFERENCES "athlitis" ("id_athliti");

ALTER TABLE "asxoleitai" ADD FOREIGN KEY ("id_athlimatos") REFERENCES "athlima" ("id_athlimatos");

ALTER TABLE "agones" ADD FOREIGN KEY ("id_athlimatos") REFERENCES "athlima" ("id_athlimatos");

ALTER TABLE "agonizetai" ADD FOREIGN KEY ("id_athliti") REFERENCES "athlitis" ("id_athliti");

ALTER TABLE "agonizetai" ADD FOREIGN KEY ("id_agona") REFERENCES "agones" ("id_agona");

ALTER TABLE "sindromi" ADD FOREIGN KEY ("id_eidous_sindromis") REFERENCES "eidos_sindromis" ("id_eidous_sindromis");

ALTER TABLE "exei" ADD FOREIGN KEY ("id_sindromiti") REFERENCES "sindromitis" ("id_sindromiti");

ALTER TABLE "exei" ADD FOREIGN KEY ("id_sindromis") REFERENCES "sindromi" ("id_sindromis");

ALTER TABLE "parakolouthisi" ADD FOREIGN KEY ("id_melous") REFERENCES "Melos" ("id_melous");

ALTER TABLE "parakolouthisi" ADD FOREIGN KEY ("id_sxolis") REFERENCES "sxoli" ("id_sxolis");

ALTER TABLE "ekpaideutis" ADD FOREIGN KEY ("id_epafis") REFERENCES "epafes" ("id_epafis");

ALTER TABLE "ekpaideuei" ADD FOREIGN KEY ("id_ekpaideuti") REFERENCES "ekpaideutis" ("id_ekpaideuti");

ALTER TABLE "ekpaideuei" ADD FOREIGN KEY ("id_sxolis") REFERENCES "sxoli" ("id_sxolis");

ALTER TABLE "drastiriotita" ADD FOREIGN KEY ("id_eksormisis") REFERENCES "eksormisi" ("id_eksormisis");

ALTER TABLE "drastiriotita" ADD FOREIGN KEY ("id_vathmou_diskolias") REFERENCES "vathmos_diskolias" ("id_vathmou_diskolias");

ALTER TABLE "simmetoxi" ADD FOREIGN KEY ("id_melous") REFERENCES "Melos" ("id_melous");

ALTER TABLE "simmetoxi" ADD FOREIGN KEY ("id_drastiriotitas") REFERENCES "drastiriotita" ("id_drastiriotitas");

ALTER TABLE "plironei" ADD FOREIGN KEY ("id_melous") REFERENCES "Melos" ("id_melous");

ALTER TABLE "plironei" ADD FOREIGN KEY ("id_simmetoxis") REFERENCES "simmetoxi" ("id_simmetoxis");

ALTER TABLE "katavalei" ADD FOREIGN KEY ("id_melous") REFERENCES "Melos" ("id_melous");

ALTER TABLE "katavalei" ADD FOREIGN KEY ("id_parakolouthisis") REFERENCES "parakolouthisi" ("id_parakolouthisis");

ALTER TABLE "Melos" ADD FOREIGN KEY ("id_melous") REFERENCES "epafes" ("id_epafis");
ALTER TABLE "Melos" ADD FOREIGN KEY ("id_vathmou_diskolias") REFERENCES "vathmos_diskolias" ("id_vathmou_diskolias");
ALTER TABLE "esoteriko_melos" ADD FOREIGN KEY ("id_es_melous") REFERENCES "Melos" ("id_melous");
ALTER TABLE "eksoteriko_melos" ADD FOREIGN KEY ("id_ekso_melous") REFERENCES "Melos" ("id_melous");
ALTER TABLE "athlitis" ADD FOREIGN KEY ("id_athliti") REFERENCES "esoteriko_melos" ("id_es_melous");
ALTER TABLE "sindromitis" ADD FOREIGN KEY ("id_sindromiti") REFERENCES "esoteriko_melos" ("id_es_melous");
ALTER TABLE "daneizetai" ADD FOREIGN KEY ("id_epafis") REFERENCES "epafes" ("id_epafis");
ALTER TABLE "daneizetai" ADD FOREIGN KEY ("id_eksoplismou") REFERENCES "eksoplismos" ("id_eksoplismou");
ALTER TABLE "kratisi_katafigiou" ADD FOREIGN KEY ("id_epafis") REFERENCES "epafes" ("id_epafis");
ALTER TABLE "kratisi_katafigiou" ADD FOREIGN KEY ("id_katafigiou") REFERENCES "katafigio" ("id_katafigiou");
ALTER TABLE "eksoflei" ADD FOREIGN KEY ("id_epafis") REFERENCES "epafes" ("id_epafis");
ALTER TABLE "eksoflei" ADD FOREIGN KEY ("id_kratisis") REFERENCES "kratisi_katafigiou" ("id_kratisis");
ALTER TABLE "asxoleitai" ADD FOREIGN KEY ("id_athliti") REFERENCES "athlitis" ("id_athliti");
ALTER TABLE "asxoleitai" ADD FOREIGN KEY ("id_athlimatos") REFERENCES "athlima" ("id_athlimatos");
ALTER TABLE "agones" ADD FOREIGN KEY ("id_athlimatos") REFERENCES "athlima" ("id_athlimatos");
ALTER TABLE "agonizetai" ADD FOREIGN KEY ("id_athliti") REFERENCES "athlitis" ("id_athliti");
ALTER TABLE "agonizetai" ADD FOREIGN KEY ("id_agona") REFERENCES "agones" ("id_agona");
ALTER TABLE "sindromi" ADD FOREIGN KEY ("id_eidous_sindromis") REFERENCES "eidos_sindromis" ("id_eidous_sindromis");
ALTER TABLE "exei" ADD FOREIGN KEY ("id_sindromiti") REFERENCES "sindromitis" ("id_sindromiti");
ALTER TABLE "exei" ADD FOREIGN KEY ("id_sindromis") REFERENCES "sindromi" ("id_sindromis");
ALTER TABLE "parakolouthisi" ADD FOREIGN KEY ("id_melous") REFERENCES "Melos" ("id_melous");
ALTER TABLE "parakolouthisi" ADD FOREIGN KEY ("id_sxolis") REFERENCES "sxoli" ("id_sxolis");
ALTER TABLE "ekpaideutis" ADD FOREIGN KEY ("id_epafis") REFERENCES "epafes" ("id_epafis");
ALTER TABLE "ekpaideuei" ADD FOREIGN KEY ("id_ekpaideuti") REFERENCES "ekpaideutis" ("id_ekpaideuti");
ALTER TABLE "ekpaideuei" ADD FOREIGN KEY ("id_sxolis") REFERENCES "sxoli" ("id_sxolis");
ALTER TABLE "drastiriotita" ADD FOREIGN KEY ("id_eksormisis") REFERENCES "eksormisi" ("id_eksormisis");
ALTER TABLE "drastiriotita" ADD FOREIGN KEY ("id_vathmou_diskolias") REFERENCES "vathmos_diskolias" ("id_vathmou_diskolias");
ALTER TABLE "simmetoxi" ADD FOREIGN KEY ("id_melous") REFERENCES "Melos" ("id_melous");
ALTER TABLE "simmetoxi" ADD FOREIGN KEY ("id_drastiriotitas") REFERENCES "drastiriotita" ("id_drastiriotitas");
ALTER TABLE "plironei" ADD FOREIGN KEY ("id_melous") REFERENCES "Melos" ("id_melous");
ALTER TABLE "plironei" ADD FOREIGN KEY ("id_simmetoxis") REFERENCES "simmetoxi" ("id_simmetoxis");
ALTER TABLE "katavalei" ADD FOREIGN KEY ("id_melous") REFERENCES "Melos" ("id_melous");
ALTER TABLE "katavalei" ADD FOREIGN KEY ("id_parakolouthisis") REFERENCES "parakolouthisi" ("id_parakolouthisis");
